### ISSUE TITLE
Add support for tools not created by InterMine

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes-tool-store#4]
e.g. under another namespace than @intermine, or no namespace at all. Low priority for now, perhaps pick back up if we have a genuine use case for this.

**Comment by heralden** [comment]
If I understand you correctly, this **does** work. Any npm package with the *bluegenes-intermine-tool* keyword will pop up in the bluegenes tool store page, to be optionally installed, and the cli tool lets you install any package. The only difference is that only the intermine scoped tools get automatically installed on initialisation.

**Comment by yochannah** [comment]
This might be the easiest ticket ever then :D 

What about the @intermine filepath?

**Comment by heralden** [comment]
Filepaths for other packages will work similarly, dumping it into `tools/<scope>/<package>` or for when the package doesn't have a scope, `tools/<package>`.

Closing ticket as we discussed.
